### ISSUE TITLE
Issue report "Types"

### ISSUE THREAD

**Issue by jannielung** [CaravanTransit/Transit-Talk#116]
The "Types" field in the issue report should actually be labeled "Issue Category" for specificity. This should also contain a check box for each of the 7 issue categories listed in the wireframes: Delays, Cleanliness, Crowding, Safety, Accessibility, Staff, and Other (text field, not check box).

**Comment by shrubin2** [comment]
How were these specific categories/labels decided upon? I'm not sure what a "staff" category means...

**Comment by AcademyInPeril** [comment]
@shrubin2, I know we talked about this in person and are advancing functionality around it, but I wanted to provide an answer here in the issue as well for everybody who wasn't part of that conversation.

These categories are the result of surveys and semi-structured conversation over the last few months to elicit general descriptions of the issues people face on transit. They're not absolutely set in stone, but these ones are the likely ones we're going with for the MVP.

**Comment by EvanGrillo** [comment]
@jannielung @AcademyInPeril Do you want me to create a `types` or `issue_categories` table and then add it to the submit issue form? Otherwise the markup form change will be illustrative & you won't capture the category
