### ISSUE TITLE
Implement New Issue Report Flow in Database

### ISSUE THREAD

**Issue by AcademyInPeril** [CaravanTransit/Transit-Talk#123]
Building off of the UI implementation work being done in #75, this issue seeks to rearchitect our database somewhat to reflect the most recent flow of the issue report form.

## Detailed Description
Currently, our database architecture reflects the fields present in the live prototype of the application deployed on Heroku. However, the issue report form has changed significantly since then (see the Marvel prototype here: https://marvelapp.com/g49gbf9/screen/52878563), and schema will need to be changed to accommodate information that's present in the latest version of the form.

## Possible Implementation
This issue is interlocked with #75 somewhat, so whoever tackles it should be in close collaboration with anybody working on #75. This new database architecture can be implemented before the UI is built out, but the UI buildout won't function properly until the database architecture is finished.

**Comment by EvanGrillo** [comment]
At minimum I need the table names that will be added or changed + the column names/types

If you provide this in a simple & clear format, the commit will include one migration file

### Column Types:
```
:binary
:boolean
:date
:datetime
:decimal
:float
:integer
:primary_key
:string
:text
:time
:timestamp
```

**Comment by AcademyInPeril** [comment]
FYI, @sinclairtarget implemented some automated annotation of database fields in #127. I'm not sure if the automated annotation will help, but thought I'd mention it here.

**Comment by AcademyInPeril** [comment]
After investigation, it seems like we don't currently require any DB changes. Closing.
