### ISSUE TITLE
Implement new issue report creation flow

### ISSUE THREAD

**Issue by AcademyInPeril** [CaravanTransit/Transit-Talk#75]
Reorient the report creation process around the screen-by-screen flow discussed on 2/20 and 2/27. This flow is as follows, provided by @jannielung in the notes from our 2/20 meeting at Chi Hack Night.

UI/UX decision tree: 
-Homepage displays issue visualization and Create an Issue Report button
-Create real-time or past issue?

Create a real-time issue:
1) App will pull up nearest stops and possible train/bus lines for user to select (based on GPS coordinates)
2) User selects category of issue
3) User inputs issue via freeform text

Create a past issue:
1) User selects time and date
2) User selects bus/train line
3) User selects station/stop
4) User selects category of issue
5) User inputs issue via freeform text

Styling of this will be determined through further UI/UX conversation and prototyping, but the logic can begin being implemented immediately.

**Comment by jannielung** [comment]
The design and logic has evolved now such that there is less of a distinction between real-time and past reporting. If you look at the wireframes for Issue Reporting Flow Design 3.0, the user has the ability to backdate an issue report. 

https://www.figma.com/file/QNnIzW2XehQJULm4tLv4ABQo/Caravan_UX-Design-Drafts_Nadeen

The app can still predict the train or bus based on GPS coordinates, but the users always have the ability to select the train/bus themselves.

**Comment by vkoves** [comment]
Relevant design from Figma:
![image](https://user-images.githubusercontent.com/3187531/45894742-ea638400-bd94-11e8-8150-4ac621b1efce.png)

**Comment by jannielung** [comment]
The wireframe shows the time and date field to allow users to input a future date for the issue. It should be updated to reflect only past or current issue dates and times.

**Comment by AcademyInPeril** [comment]
The current Marvel wireframes (https://marvelapp.com/g49gbf9/screen/52878563) should be used to implement this flow. However, the new flow requires the database to be mildly rearchitected. Since those skill sets might be somewhat divergent, I've split this issue off so that #123 serves as the database portion of the work.

This issue is interlocked with #123 somewhat, so whoever tackles it should be in close collaboration with anybody working on #123. The new database architecture can be implemented before the UI is built out, but the UI buildout won't function properly until the database architecture is finished.

**Comment by AcademyInPeril** [comment]
This is encapsulated in #130, so this issue is being closed.
